version: "3.7"

services:
  phpfpm:
    image: hiberusmagento/php:<php_version>
    volumes: &appvolumes
      - sockdata:/sock
      - ../.composer:/var/www/.composer:delegated
      - ../.composer:/var/www/html/var/composer_home:delegated
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      COMPOSER_VERSION: <composer_version>
    depends_on:
      - db
      - search
      - redis
      - mailhog
      - rabbitmq
      
  nginx:
    image: hiberusmagento/nginx:1.18
    volumes: *appvolumes
    depends_on:
      - phpfpm

  db:
    image: hiberusmagento/mariadb:<mariadb_version>
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    command: [ '--max_allowed_packet=64M', '--default-authentication-plugin=mysql_native_password', '--sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' ]
    volumes:
      - dbdata:/var/lib/mysql

  search:
    image: hiberusmagento/search:<search_version>
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - opensearchdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  varnish:
    image: hiberusmagento/varnish:<varnish_version>
    tty: true
    ports:
      - 80:6081
    depends_on:
      - nginx

  redis:
    image: hiberusmagento/redis:<redis_version>
    volumes:
      - redisdata:/data:delegated

  mailhog:
    image: hiberusmagento/mailhog:1
    ports:
      - 8025:8025

  rabbitmq:
    image: hiberusmagento/rabbitmq:3.9
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  hitch:
    image: hiberusmagento/hitch:1.7
    ports:
      - 443:443
    depends_on:
      - varnish

volumes:
  dbdata:
  sockdata:
  elasticdata:
  opensearchdata:
  redisdata:
  rabbitmqdata: